name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  commits:
    name: Conventional commits
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ github.token }}

  build-esp:
    name: Build ESP firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          ldproxy: false
          cache: true

      - uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v2

      - name: Build ossm-alt-m57aim
        run: just build-ossm-alt
